version: 2
jobs:
  build:
    docker:
      - image: satellitex/alpine-cmake-git:latest
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: cmake
          command: |
            mkdir build
            cd build &&
            cmake ..
      - run:
          name: make
          command: make
      - run:
          name: test
          command: make test